iam_username = "username_from_module"
iamgroup_name = "groupname_from_module"
sg_name = "sg_from_module"
amiid = "ami-02c7d3513f9fdf3f6"
instancetype = "t2.micro"
instancename = "instance_from_module"